Fix build error due to non-existing window.loadTimeData
We need to import loadTimeData from the internal module and
use it from there instead of accessing window.loadTimeData.

ERROR in /home/work/brave-browser/src/brave/components/brave_welcome_ui/reducers/welcome_reducer.ts
in /home/work/brave-browser/src/brave/components/brave_welcome_ui/reducers/welcome_reducer.ts(47,40)
TS2339: Property \'loadTimeData\' does not exist on type \'Window & typeof globalThis\'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! brave-core@1.28.4 web-ui: `webpack --config
components/webpack/webpack.config.js --progress --colors "--mode=development"
"brave_welcome=/home/work/brave-browser/src/brave/components/brave_welcome_ui/brave_welcome.tsx"`

Traceback (most recent call last):
  File "/home/work/brave-browser/src/out/Component/../../brave/script/transpile-web-ui.py", line 118, in <module>
    sys.exit(main())
  File "/home/work/brave-browser/src/out/Component/../../brave/script/transpile-web-ui.py", line 31, in main
    transpile_web_uis(args.production, webpack_gen_dir, root_gen_dir,
  File "/home/work/brave-browser/src/out/Component/../../brave/script/transpile-web-ui.py", line 98, in transpile_web_uis
    execute_stdout(args, env)
  File "/home/work/brave-browser/src/brave/script/lib/util.py", line 192, in execute_stdout
    execute(argv, env)
  File "/home/work/brave-browser/src/brave/script/lib/util.py", line 180, in execute
    raise e
  File "/home/work/brave-browser/src/brave/script/lib/util.py", line 173, in execute
    output = subprocess.check_output(argv, stderr=subprocess.STDOUT,
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['npm', 'run', 'web-ui', '--', '--mode=development', 'brave_welcome=/home/work/brave-browser/src/brave/components/brave_welcome_ui/brave_welcome.tsx']' returned non-zero exit status 2.